version: '3.8'

services:
  chatbot-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: react-chatbot-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_INLINE=true
    networks:
      - chatbot-network
    command: npm run dev

networks:
  chatbot-network:
    driver: bridge
