name: Push to Docker Hub

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  workflow_dispatch:

env:
  DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/react-chatbot

jobs:
  push:
    runs-on: ubuntu-latest
    if: secrets.DOCKER_USERNAME != ''

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ steps.version.outputs.tag }}
            ${{ env.DOCKER_REPO }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPO }}
          short-description: React Chatbot with Google Gemini AI
          description: |
            A modern React chatbot powered by Google's Generative AI (Gemini 2.0 Flash).
            
            Features:
            - Real-time AI responses
            - Beautiful gradient UI
            - Responsive design
            - Docker & Kubernetes ready
            - Production-ready configuration
          readme-filepath: ./README.md
